### ISSUE TITLE
Create version to get Zenodo DOI

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/R-in-Jupyter-with-Binder#6]
After the first draft is ready to send out then create tag `v0.0.1` to trigger [Zenodo](https://zenodo.org/) to generate the DOI for the repo. Add this DOI badge to the README.

**Comment by RaoOfPhysics** [comment]
Just FYI, but you might want to keep an eye on this: https://github.com/zenodo/zenodo/issues/1416

**Comment by matthewfeickert** [comment]
@RaoOfPhysics I've subscribed to the Issue. :+1:

**Comment by matthewfeickert** [comment]
Resolved by commit b8653f63345a86990fea87e502476a96466ab39a
