### ISSUE TITLE
Add links to Noam Ross's nyhackr 2018 talk

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/R-in-Jupyter-with-Binder#7]
Thanks to @RaoOfPhysics pointing out [Noam](https://github.com/noamross)'s [nyhackr](https://nyhackr.org/) 2018 talk: [Docker for the UseR](https://github.com/noamross/nyhackr-docker-talk), it should get added in as a resource and linked to where relevant.

**Comment by RaoOfPhysics** [comment]
Might be worth tagging @noamross so he's aware that you're pointing to his work. :)
