### ISSUE TITLE
Add Binder support for R Markdown

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/R-in-Jupyter-with-Binder#8]
@RaoOfPhysics and friends have done it again! As [pointed out here](https://github.com/matthewfeickert/R-in-Jupyter-with-Binder/issues/5#issuecomment-406539812) and first done in [nbrmd Issue 19](https://github.com/mwouts/nbrmd/issues/19) it is possible to **interactively** support R Markdown in a Jupyter notebook on Binder(!!!)!

This should be added in.

**Comment by RaoOfPhysics** [comment]
I have literally done nothing (besides get the relevant people to talk). :P But thanks for the shoutout! <3

**Comment by matthewfeickert** [comment]
A highly non-negligible step in GTD, if you ask me. :)
